Remove hardcoded values for PROJECT_NAME_PYTHON

diff --git a/delete-local-config b/delete-local-config
--- a/delete-local-config
+++ b/delete-local-config
@@ -2,7 +2,12 @@
 
 cd $(dirname "$0")
 
-keys_file_path="$(pwd)/app/makenget/keys.py"
+if [ "$PROJECT_NAME_PYTHON" == "" ]; then
+  echo "PROJECT_NAME_PYTHON not set. Aborting..."
+  exit 1
+fi
+
+keys_file_path="$(pwd)/app/$PROJECT_NAME_PYTHON/keys.py"
 if [ -f $keys_file_path ]; then
   echo "Removing '$keys_file_path'..."
   rm $keys_file_path
@@ -10,7 +15,7 @@ else
   echo "Not found: '$keys_file_path'. Skipping..."
 fi
 
-config_file_path="$(pwd)/app/makenget/server_config.py"
+config_file_path="$(pwd)/app/$PROJECT_NAME_PYTHON/server_config.py"
 if [ -f $config_file_path ]; then
   echo "Removing '$config_file_path'..."
   rm $config_file_path
